version: "3.9"
services:
  bot:
    build: .
    volumes:
      - bot:/usr/GenericFeed
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017
    restart: "on-failure"
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
volumes:
  bot:
